ARG DB_VERSION

FROM wardenenv/mariadb:${DB_VERSION} as mariadb-setup

ENV DB_NAME magento
ENV DB_PASS magento
ENV DB_USER magento

# Prevent executing server on build run
RUN ["sed", "-i", "s/exec \"$@\"//", "/usr/local/bin/docker-entrypoint.sh"]
RUN mkdir /setup-db/ && chown mysql:mysql /setup-db/ && chmod 0777 /setup-db/

COPY sample.db.sql /docker-entrypoint-initdb.d/
COPY docker-build-data.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-build-data.sh
RUN ["docker-build-data.sh", "docker-entrypoint.sh", \
     "mariadbd", "--datadir", "/setup-db/", "--aria-log-dir-path", "/setup-db/"]

FROM wardenenv/mariadb:${DB_VERSION}

ENV DB_NAME magento
ENV DB_PASS magento
ENV DB_USER magento

ENV MYSQL_DATABASE=$DB_NAME
ENV MYSQL_PASSWORD=$DB_PASS
ENV MYSQL_ROOT_PASSWORD=$DB_PASS
ENV MYSQL_USER=$DB_USER

COPY --from=mariadb-setup /setup-db /var/lib/mysql