FROM wardenenv/mysql:8.0 as mysql-setup

ENV DB_NAME magento
ENV DB_PASS magento
ENV DB_USER magento

# Prevent executing server on build run
RUN ["sed", "-i", "s/exec \"$@\"//", "/usr/local/bin/docker-entrypoint.sh"]

COPY sample.db.sql /docker-entrypoint-initdb.d/
COPY docker-build-data.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-build-data.sh
RUN ["docker-build-data.sh", "docker-entrypoint.sh", "mysqld", "--datadir", "/setup-mysql"]

FROM wardenenv/mysql:8.0

ENV MYSQL_DATABASE magento
ENV MYSQL_PASSWORD magento
ENV MYSQL_ROOT_PASSWORD magento
ENV MYSQL_USER magento

COPY --from=mysql-setup /setup-mysql /var/lib/mysql