ARG DB_VERSION

FROM percona/percona-server:${DB_VERSION}-multi as mysql-setup

ENV MYSQL_DATABASE magento
ENV MYSQL_PASSWORD magento
ENV MYSQL_ROOT_PASSWORD magento
ENV MYSQL_USER magento
ENV MYSQL_INIT_ONLY 1

COPY sample.db.sql /docker-entrypoint-initdb.d/

USER root
RUN mkdir -p "/setup/db" && chown -R mysql:root "/setup/db"
USER mysql

RUN ["/docker-entrypoint.sh", "mysqld", "--datadir", "/setup/db"]

FROM percona/percona-server:${DB_VERSION}-multi

ENV MYSQL_DATABASE magento
ENV MYSQL_PASSWORD magento
ENV MYSQL_ROOT_PASSWORD magento
ENV MYSQL_USER magento

COPY --from=mysql-setup /setup/db /var/lib/mysql