FROM wardenenv/mariadb:10.6 as mariadb-setup

ENV DB_NAME magento
ENV DB_PASS magento
ENV DB_USER magento

# Prevent executing server on build run
RUN ["sed", "-i", "s/exec \"$@\"//", "/usr/local/bin/docker-entrypoint.sh"]

COPY sample.db.sql /docker-entrypoint-initdb.d/
COPY docker-build-data.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-build-data.sh
RUN ["docker-build-data.sh", "docker-entrypoint.sh", \
     "mariadbd", "--datadir", "/setup-mariadb", "--aria-log-dir-path", "/setup-mariadb"]

FROM wardenenv/mariadb:10.6

ENV DB_NAME magento
ENV DB_PASS magento
ENV DB_USER magento

ENV MYSQL_DATABASE=$DB_NAME
ENV MYSQL_PASSWORD=$DB_PASS
ENV MYSQL_ROOT_PASSWORD=$DB_PASS
ENV MYSQL_USER=$DB_USER

COPY --from=mariadb-setup /setup-mariadb /var/lib/mysql